config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      delete :purge_avatar
    end
  end
  # devise_for :users
  resources :telegrams, only: :index
  root 'homes#index'
  post '/group_message' => 'telegrams#group_message'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
end

app/models/telegram.rb
class Telegram < ApplicationRecord
end

app/controllers/telegrams_controller.rb
class TelegramsController < ApplicationController
  skip_before_action :authenticate_user!
  # GET /telegrams or /telegrams.json
  def index
    res = HTTParty.get("https://api.telegram.org/#{ENV['BOT_TOKEN']}/getChat?chat_id=#{ENV['CHAT_ID']}")
    @title = res['result']['title']
    @id = res['result']['id']
  end

  def group_message
    HTTParty.post("https://api.telegram.org/#{ENV['BOT_TOKEN']}/sendMessage",
                  headers: {
                    'Content-Type' => 'application/json'
                  },
                  body: {
                    chat_id: ENV['CHAT_ID'],
                    text: params[:message]
                  }.to_json)

    redirect_to root_path, notice: 'success'
  end
end

app/helpers/telegrams_helper.rb
module TelegramsHelper
end

app/views/telegrams/_form.html.erb
<%= form_with(model: telegram) do |form| %>
  <% if telegram.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(telegram.errors.count, "error") %> prohibited this telegram from being saved:</h2>

      <ul>
        <% telegram.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/telegrams/_telegram.html.erb
<div id="<%= dom_id telegram %>">
</div>

app/views/telegrams/edit.html.erb
<h1>Editing telegram</h1>

<%= render "form", telegram: @telegram %>

<br>

<div>
  <%= link_to "Show this telegram", @telegram %> |
  <%= link_to "Back to telegrams", telegrams_path %>
</div>

app/views/telegrams/index.html.erb
<h1>Telegram</h1>
<h5>Group name: </h5><%=@title %> </h5>
<h5>Group id: </h5><%= @id %> </h5>

<%= form_tag group_message_path, method: :post do %>
  <%= text_field_tag :message, nil, required: true, placeholder: "Enter message" %>
  <%= submit_tag "Send message" %>
<% end %>

<p style="color: green"><%= notice %></p>

<!-- <%= link_to "Create message", "https://api.telegram.org/bot6379697986:AAGSPiv82e1YWf9UAOsbilii8OvyxQrbGU0/sendMessage?chat_id=-4118806600&text=anhne" %> -->

app/views/telegrams/new.html.erb
<h1>New telegram</h1>

<%= render "form", telegram: @telegram %>

<br>

<div>
  <%= link_to "Back to telegrams", telegrams_path %>
</div>

app/views/telegrams/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @telegram %>

<div>
  <%= link_to "Edit this telegram", edit_telegram_path(@telegram) %> |
  <%= link_to "Back to telegrams", telegrams_path %>

  <%= button_to "Destroy this telegram", @telegram, method: :delete %>
</div>