config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    member do
      delete :purge_avatar
    end
  end
  # devise_for :users
  resources :telegrams, only: :index
  root 'homes#index'
  post '/group_message' => 'telegrams#group_message'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  delete "attachments/:id/purge", to: "attachments#purge", as: "purge_attachment"
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: 'users/registrations'
  }
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :avatar
  has_many_attached :images

  has_rich_text :description

  enum status: { draft: 'draft', published: 'published', banned: 'banned' }, _default: 'draft'

  validates :title, presence: true
  validates :avatar, attached: true,
                     # dimension: { width: { min: 800, max: 2400 } },
                     content_type: %i[png jpg jpeg]
  # , size: { less_than: 100.kilobytes , message: 'is not given between size' }

  validates :images, attached: true, limit: { min: 1, max: 3 }, content_type: %i[png jpg jpeg mp3 mp4 pdf]

  has_one_attached :qr_code
  has_one_attached :barcode

  after_create :generate_qr
  def generate_qr
    GenerateQr.call(self)
    GenerateBarcode.call(self)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy purge_avatar]
  invisible_captcha only: %i[create update]

  # GET /articles or /articles.json
  def index
    @pagy, @articles = pagy(Article.order(created_at: :desc))
  end

  # GET /articles/1 or /articles/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: @article.id.to_s
        # {@article.id} la pdf file name
        # neu khong chi dinh template thi se lay theo ten action
        # render pdf: "#{@article.id}", template: "articles/ten_template" ex: articles/show
      end
    end
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if save_article_and_send_telegram_message
        format.html { handle_html_response }
        # format.json { handle_json_response }
      else
        format.html { render_new_html }
        # format.json { render_errors_json }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      delete_images_if_needed

      if update_article
        format.html { redirect_to article_url(@article), notice: 'Article was successfully updated.' }
        # format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        # format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!
    @article.images.purge

    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purge_avatar
    @article.avatar.purge
    redirect_back fallback_location: root_path, notice: 'success'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :content, :avatar, :description, :status, images: [], tags: [])
  end

  def save_article_and_send_telegram_message
    if @article.save
      TelegramMailer.send_group_message(params[:article][:content]).deliver_now
      true
    else
      false
    end
  end

  def handle_html_response
    redirect_to article_url(@article), notice: 'Article was successfully created and sent to telegram.'
  end

  # def handle_json_response
  #   render :show, status: :created, location: @article
  # end

  def render_new_html
    render :new, status: :unprocessable_entity
  end

  # def render_errors_json
  #   render json: @article.errors, status: :unprocessable_entity
  # end

  def delete_images_if_needed
    @article.images.purge if article_params[:avatar]
  end

  def update_article
    @article.update(article_params)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def resize_image_tag(image_path, width, height)
    image_tag image_path, style: "width: #{width}px; height: #{height}px;"
  end
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="main">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Avatar:</strong>
    <% if article.avatar.attached? %>
      <%= resize_image_tag(article.avatar, 200, 200) %>
      <%= link_to "Delete avatar", purge_avatar_article_path(@article), data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure to delete avatar?"
      } %>
      <!-- <%= button_to "Delete avatar", purge_avatar_article_path(article), method: :delete%> -->
    <% end %>
  </p>

  <p>
    <strong>Images:</strong>
    <% if article.images.attached? %>
      <div class="file-container">
        <% article.images.each do |attachment| %>
          <% if attachment.image? %>
            <div class="file-thumbnail">
              <%= resize_image_tag(attachment, 250, 250) %>
              <%= link_to "Delete attachment", purge_attachment_path(attachment), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure to delete attachment?"
              } %>
            </div>
          <% elsif attachment.audio? %>
            <div class="file-thumbnail">
              <audio controls>
                <source src="<%= rails_blob_url(attachment) %>" type="<%= attachment.content_type %>"/>
              </audio>
              <%= link_to "Delete attachment", purge_attachment_path(attachment), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure to delete attachment?"
              } %>
            </div>
          <% elsif attachment.video? %>
            <div class="file-thumbnail">
              <video controls width="480">
                <source src="<%= rails_blob_url(attachment) %>" type="<%= attachment.content_type %>"/>
              </video>
              <%= link_to "Delete attachment", purge_attachment_path(attachment), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure to delete attachment?"
              } %>
            </div>
          <% else %>
            <%= link_to attachment.filename, rails_blob_path(attachment, disposition: "attachment") %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= article.content %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- log time  -->
  <%= invisible_captcha %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div><br>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Article.statuses.keys, include_blank: true %>
  </div><br>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div><br>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div><br>

  <%= form.label :tags %>
  <br>
  <% Contants::TAGS.each do |key| %>
    <br>
    <%= form.check_box :tags, { multiple: true, checked: form.object.tags&.include?(key.to_s) }, key, nil %>
    <%= form.label key %>
  <% end %><br>

  <div>
    <%= form.label :avatar%>
    <%= form.file_field :avatar %>
  </div><br>

  <div>
    <%= form.label :images%>
    <%= form.file_field :images, multiple: true %>
  </div><br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="main">
  <h1>Articles</h1>
  <%= link_to "New article", new_article_path %>
  <br>
  <br>
  Total Articles:
  <b><%= @articles.count %></b>/<b><%= Article.count %></b>
  <br>
  <%== pagy_nav(@pagy) %>
  <br>
  <%== pagy_info(@pagy) %>
  <br>
  <%== pagy_bootstrap_nav(@pagy) %>

  <table class="article-table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Avatar</th>
        <th>Title</th>
        <th>Status</th>
        <th>Tags</th>
        <th>Content</th>
        <th>Images</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each_with_index do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= resize_image_tag(article.avatar, 50, 50) if article.avatar.attached? %></td>
          <td>
            <%= image_tag(article.qr_code) if article.qr_code.attached? %>
            <%= image_tag(article.barcode) if article.barcode.attached? %>
          </td>
          <td><%= article.status %></td>

          <td>
            <% if !article.tags.empty? %>
              <% article.tags.each do |tag| %>
                <span class="tag"><%= tag %></span>
                <% unless tag == article.tags.last %>
                  <%= ", " %>
                <% end %>
              <% end %>
            <% end %>
          </td>

          <td><%= article.content %></td>
          <td>
            <% if article.images.attached? %>
              <div class="file-container">
                <% article.images.each do |attachment| %>
                  <% if attachment.image? %>
                    <div class="file-thumbnail">
                      <%= resize_image_tag(attachment, 250, 250) %>
                    </div>
                  <% elsif attachment.audio? %>
                    <div class="file-thumbnail">
                      <audio controls>
                        <source src="<%= rails_blob_url(attachment) %>" type="<%= attachment.content_type %>"/>
                      </audio>
                    </div>
                  <% elsif attachment.video? %>
                    <div class="file-thumbnail">
                      <video controls width="480">
                        <source src="<%= rails_blob_url(attachment) %>" type="<%= attachment.content_type %>"/>
                      </video>
                    </div>
                  <% else %>
                    <%= link_to attachment.filename, rails_blob_path(attachment, disposition: "attachment") %>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </td>
          <td><%= link_to 'Show', article %></td>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Print', article_path(article, format: :pdf) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

<style>
  .article-table th,
  .article-table td {
    padding: 30px; /* Thiết lập khoảng cách bên trong các ô */
  }

  .article-table th {
    background-color: white; /* Tùy chọn: màu nền cho các tiêu đề */
  }

  .article-table td {
    border: none; /* Tùy chọn: đường viền cho ô */
  }

  .article-table th:first-child,
  .article-table td:first-child {
    padding-left: 20px; /* Tùy chọn: tăng khoảng cách bên trái của cột đầu tiên */
  }

  .article-table th:last-child,
  .article-table td:last-child {
    padding-right: 20; /* Tùy chọn: tăng khoảng cách bên phải của cột cuối cùng */
  }
</style>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/articles/show.pdf.erb
PDF generation date:
<%= Time.zone.now %>
<table class="article-table">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @article.id %></td>
        <td><%= @article.title %></td>
        <td><%= @article.content %></td>
      </tr>
  </tbody>
</table>
<br>

<style>
  .article-table th,
  .article-table td {
    padding: 30px; /* Thiết lập khoảng cách bên trong các ô */
  }

  .article-table th {
    background-color: white; /* Tùy chọn: màu nền cho các tiêu đề */
  }

  .article-table td {
    border: none; /* Tùy chọn: đường viền cho ô */
  }

  .article-table th:first-child,
  .article-table td:first-child {
    padding-left: 20px; /* Tùy chọn: tăng khoảng cách bên trái của cột đầu tiên */
  }

  .article-table th:last-child,
  .article-table td:last-child {
    padding-right: 20px; /* Tùy chọn: tăng khoảng cách bên phải của cột cuối cùng */
  }
</style>